name: pergel
version: 0.0.0
services:
  test-postgres:
    image: postgres:16-alpine
    volumes:
      - type: volume
        source: test-postgres
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  test-redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - test-redis:/data
    command:
      - redis-server
      - --appendonly yes
      - --requirepass redis
volumes:
  test-postgres: {}
  test-redis: {}
